###############
# User inputs #
###############

SAMPLES = [
    "cd4_rep1",
    "cd8_rep1"
]

############
# Workflow #
############

rule all:
    input:
        "results/multiqc/fastqc_report.html",

rule fastqc:
    input:
        fastq="data/{sample}_{read}.fastq.gz"
    output:
        html="results/fastqc/{sample}_{read}_fastqc.html"
    threads: 2
    resources:
        mem_mb=2000,
        runtime=10,
        slurm_partition="short",
    shell:
        """
        fastqc --outdir results/fastqc -t {threads} {input.fastq}
        """

rule multiqc_fastqc:
    input:
        expand("results/fastqc/{sample}_{read}_fastqc.html", sample=SAMPLES, read=["read1", "read2"]),
    output:
        html="results/multiqc/fastqc_report.html",
    threads: 1
    resources:
        mem_mb=2000,
        runtime=10,
        slurm_partition="short",
    shell:
        """
        multiqc results/fastqc --outdir results/multiqc --filename fastqc_report.html
        """
